#!/bin/sh
#
#  This role installs Puppet upon the new guest system.
#
#  It must make sure that the server is not running before it exits
# otherwise the temporary mounted directory will not be unmountable.
#

prefix=$1

#
#  Source our common functions - this will let us install a Debian package.
#
if [ -e /usr/share/xen-tools/common.sh ]; then
    . /usr/share/xen-tools/common.sh
else
    echo "Installation problem"
fi

#
# Log our start
#
logMessage Script $0 starting


#
#  Install puppet
#

chroot ${prefix} /usr/bin/wget https://apt.puppetlabs.com/puppetlabs-release-precise.deb -O /root/puppetlabs-release-precise.deb
chroot ${prefix} /usr/bin/dpkg -i /root/puppetlabs-release-precise.deb
chroot ${prefix} /usr/bin/apt-get update
installDebianPackage puppet

#
#  Configure puppet
#

chroot ${prefix} /bin/rm -rf /etc/puppet
git clone /etc/puppet  ${prefix}/etc
cp -a /root/.ssh/puppet ${prefix}/root/.ssh/puppet

cat <<EOF > ${prefix}/etc/cron.d/puppet
# Pull latest puppet configuration
0 * * * * root  cd /etc/puppet && git pull && ./puppet_apply.sh
EOF

cat <<EOF1 > ${prefix}/root/.ssh/config
Host git.gnulug.org
    User git
    HostName git.gnulug.org
    IdentityFile ~/.ssh/puppet
EOF1

#
#  Log our finish
#

logMessage Script $0 finished
